version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies using uv
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock

  runapp:
    desc: Run streamlit_app.py with environment from .env
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run streamlit run streamlit_app.py
    interactive: true

  api_run:
    desc: Run FastAPI image API on port 8000
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run uvicorn fastapi_app:app --host 0.0.0.0 --port 8000
    interactive: true

  api_dev:
    desc: Run FastAPI image API with auto-reload
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload
    interactive: true

  api_tls_cert:
    desc: Create local self-signed TLS cert for HTTPS API testing
    cmds:
      - mkdir -p certs
      - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout certs/localhost-key.pem -out certs/localhost.pem -subj "/CN=localhost"

  api_run_https:
    desc: Run FastAPI image API over HTTPS on port 8443
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run uvicorn fastapi_app:app --host 0.0.0.0 --port 8443 --ssl-keyfile certs/localhost-key.pem --ssl-certfile certs/localhost.pem
    interactive: true

  api_dev_https:
    desc: Run FastAPI image API over HTTPS with auto-reload on port 8443
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run uvicorn fastapi_app:app --host 0.0.0.0 --port 8443 --reload --ssl-keyfile certs/localhost-key.pem --ssl-certfile certs/localhost.pem
    interactive: true

  api_health:
    desc: Check local API health endpoint
    cmds:
      - curl -fsS http://localhost:8000/health

  api_health_https:
    desc: Check local HTTPS API health endpoint
    cmds:
      - curl -k -fsS https://localhost:8443/health

  containers_up:
    desc: Start backend container stack (qdrant + fastapi) for local integration
    cmds:
      - docker network inspect neckarwave_net >/dev/null 2>&1 || docker network create neckarwave_net
      - docker rm -f nw_qdrant >/dev/null 2>&1 || true
      - docker run --rm -d --name nw_qdrant --network neckarwave_net -p 6333:6333 -p 6334:6334 -v "$(pwd)/qdrant_storage:/qdrant/storage" qdrant/qdrant:latest
      - task docker_build_fastapi_amd64
      - docker rm -f nw_fastapi >/dev/null 2>&1 || true
      - docker run --rm -d --name nw_fastapi --network neckarwave_net --env-file .env -e QDRANT_URL=http://nw_qdrant:6333 -p 8000:8000 ghcr.io/ejmiddle/fastapi-backend:latest

  containers_down:
    desc: Stop backend container stack (qdrant + fastapi)
    cmds:
      - docker stop nw_fastapi >/dev/null 2>&1 || true
      - docker stop nw_qdrant >/dev/null 2>&1 || true

  containers_ps:
    desc: Show running project containers
    cmds:
      - docker ps --filter "name=nw_fastapi" --filter "name=nw_qdrant"

  containers_logs_fastapi:
    desc: Follow logs from FastAPI backend container
    cmds:
      - docker logs -f nw_fastapi

  containers_logs_qdrant:
    desc: Follow logs from Qdrant backend container
    cmds:
      - docker logs -f nw_qdrant

  notion_check:
    desc: Run Notion access check (set NOTION_DATABASE_ID or pass as arg)
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run python scripts/check_notion_access.py {{.DATABASE_ID}} {{.CLI_ARGS}}
    vars:
      DATABASE_ID: '{{.DATABASE_ID | default ""}}'
      CLI_ARGS: '{{.CLI_ARGS | default ""}}'

  notion_copy:
    desc: Copy a Notion database schema into the same parent (set NOTION_DATABASE_ID or pass as arg)
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run python scripts/check_notion_access.py {{.DATABASE_ID}} --copy {{.CLI_ARGS}}
    vars:
      DATABASE_ID: '{{.DATABASE_ID | default ""}}'
      CLI_ARGS: '{{.CLI_ARGS | default ""}}'

  notion_copy_rows:
    desc: Copy a Notion database schema + rows into the same parent (set NOTION_DATABASE_ID or pass as arg)
    deps: [install]
    cmds:
      - set -a; source .env; set +a; uv run python scripts/check_notion_access.py {{.DATABASE_ID}} --copy --copy-rows {{.CLI_ARGS}}
    vars:
      DATABASE_ID: '{{.DATABASE_ID | default ""}}'
      CLI_ARGS: '{{.CLI_ARGS | default ""}}'

  ping_test_internet:
    desc: Run the internet ping test script
    deps: [install]
    cmds:
      - uv run python scripts/ping_test_internet.py monitor

  ping_test_internet_plot:
    desc: Plot results from the internet ping test logfile
    deps: [install]
    cmds:
      - uv run python scripts/ping_test_internet.py plot

  clean:
    desc: Clean cache and temporary files
    cmds:
      - find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

  docker_build_app:
    desc: Build amd64 image for mittwald
    cmds:
      - docker buildx build --platform linux/amd64 -t ghcr.io/ejmiddle/streamlit-hello:latest --load -f Dockerfile .
      - echo "docker images ghcr.io/ejmiddle/streamlit-hello:latest"

  docker_push_app:
    desc: Push image to GHCR
    cmds:
      - docker push ghcr.io/ejmiddle/streamlit-hello:latest
      - echo "Tip-> source .env && echo \"$GHCR_TOKEN\" | docker login ghcr.io -u ejmiddle --password-stdin"

  docker_run_app:
    desc: Run the app container locally for testing
    deps: [docker_build_app]
    cmds:
      - docker run --rm --platform linux/amd64 -p 8501:8501 -v "$(pwd)/data:/app/data" ghcr.io/ejmiddle/streamlit-hello:latest
    interactive: true

  docker_build_fastapi_amd64:
    desc: Build amd64 FastAPI backend image
    cmds:
      - docker buildx build --platform linux/amd64 -t ghcr.io/ejmiddle/fastapi-backend:latest --load -f Dockerfile.fastapi .

  docker_push_fastapi:
    desc: Push FastAPI backend image to GHCR
    cmds:
      - docker push ghcr.io/ejmiddle/fastapi-backend:latest

  docker_publish_fastapi:
    desc: Build then push FastAPI backend image to GHCR
    cmds:
      - task docker_build_fastapi_amd64
      - task docker_push_fastapi

  api_run_publish:
    desc: Build then push image for api_run deployment
    cmds:
      - task docker_publish_fastapi

  docker_run_fastapi:
    desc: Run the FastAPI backend container locally for testing
    deps: [docker_build_fastapi_amd64]
    cmds:
      - docker run --rm --platform linux/amd64 --env-file .env -p 8000:8000 ghcr.io/ejmiddle/fastapi-backend:latest
    interactive: true


  qdrant_up:
    desc: Start a local Qdrant server (latest stable)
    cmds:
      - mkdir -p qdrant_storage
      - docker run --rm -d --name qdrant -p 6333:6333 -p 6334:6334 -v "$(pwd)/qdrant_storage:/qdrant/storage" qdrant/qdrant:latest

  qdrant_down:
    desc: Stop the local Qdrant server
    cmds:
      - docker stop qdrant

  qdrant_logs:
    desc: Follow logs from the local Qdrant server
    cmds:
      - docker logs -f qdrant

  qdrant_test:
    desc: Test the local Qdrant server health endpoint
    cmds:
      - python3 scripts/test_qdrant.py
